package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import hello.Dictionary;
import hello.DictionaryRepository;

import java.util.Date;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private DictionaryRepository dictionaryRepository;

    @GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody String addNewUser (@RequestParam String word, @RequestParam String translation, @RequestParam String addDate, @RequestParam String modDate , @RequestParam Integer max_id) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Dictionary dict = new Dictionary();
        dict.setWord(word);
        dict.setTranslation(translation);
        dict.setAddDate(addDate);
        dict.setModDate(modDate);
        dict.setMax_id(max_id);
        dictionaryRepository.save(dict);
        return "Saved";


    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Dictionary> getAllWords() {
        // This returns a JSON or XML with the users
        return dictionaryRepository.findAll();
    }
}